# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about
  友链: /friend
  
# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - music/溯.mp3
    - music/mine.mp3
    - music/诀别书.mp3
    - music/七年了，他还是走不出来.mp3
    - music/《溯 Reverse》.mp3
    - music/《託された想い (被寄托的思念)—増田俊郎》.mp3
    - music/【钢琴】《所念皆星河 》.mp3
    - music/【钢琴】陈奕迅《富士山下》.mp3
    - music/【钢琴】花之舞 《Flower Dance》.mp3
    - music/【钢琴】周杰伦《反方向的钟》.mp3
    - music/【钢琴】周杰伦《青花瓷》.mp3
    - music/I Really Like You.mp3


# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/zlbeatdragon.jpg
  - /img/zhongliANDdada.jpg
  - /img/welcome-cover.jpg

# 是否显示Twitter分享卡片图像(图像尺寸要求：1200*600，creatorid不需要带@符号。注意：链接必须是完整url，否则Twitter将无法读取图片信息）
twitterpic:
  enable: false
  src: https://bangdream.moe/img/ident.png
  creatorid: yourtwitteridhere

# 是否使用mathjax
mathjax: true


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    #facebook: /
    #twitter: /
    github: https://github.com/0bluewhale0
    wechat: /img/wechat.png
    #email: 
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 京ICP备2023004067号
    # 链接地址
    link: https://beian.miit.gov.cn/

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: true
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '86a92b9df49e55c6beaf'
    # 应用秘钥
    clientSecret: 'b740ee88f80bbd33b4109f0c18a4f049a00a6439'
    # issue仓库名
    repo: 'CommentRepo'
    # Github名
    owner: '0bluewhale0'
    # Github名
    admin: ['0bluewhale0']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: true

# 网站关键字
keywords: shanzhihan's blog

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/icoon.png

# rss文件
rss: atom.xml

#hexo toc 目录
toc:
  maxDepth: 3


